create table product(
id int auto_increment,
primary key(id),
barcode int,
name varchar(255),
cost int,
count int,
feature varchar(255),
brand varchar(255),
inch int,
quality varchar(255),
 radioWave varchar(255),
 sourceEnergyType varchar(255),
 size int,
 material varchar(255),
 typeCover varchar(255),
 language varchar(255),
 publisher varchar(255),
 format varchar(255),
 page int,
 type varchar(255),
 periodPublish varchar(255),
 magazineType varchar(255),
 productType varchar(255),
 shoesType varchar(255)
);
